/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lighting_NativeLibrary */

#ifndef _Included_com_example_lighting_NativeLibrary
#define _Included_com_example_lighting_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lighting_NativeLibrary
 * Method:    initGraphics
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_lighting_NativeLibrary_initGraphics
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_lighting_NativeLibrary
 * Method:    update
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_lighting_NativeLibrary_update
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_lighting_NativeLibrary
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lighting_NativeLibrary_render
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lighting_NativeLibrary
 * Method:    loadResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lighting_NativeLibrary_loadResources
  (JNIEnv *, jclass);


/*
 * Class:     com_example_lighting_NativeLibrary
 * Method:    setAssetManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lighting_NativeLibrary_setAssetManager
  (JNIEnv *, jclass /*this*/, jclass /*AssetManager pointer*/);

#ifdef __cplusplus
}
#endif
#endif
