/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_simpleTriangle_NativeLibrary */

#ifndef _Included_com_example_simpleTriangle_NativeLibrary
#define _Included_com_example_simpleTriangle_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_simpleTriangle_NativeLibrary
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_simpleTriangle_NativeLibrary_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_simpleTriangle_NativeLibrary
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_simpleTriangle_NativeLibrary_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
