/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

/* Header for class com_example_chap01_NativeLibrary */

#ifndef _Included_com_example_chap01_NativeLibrary
#define _Included_com_example_chap01_NativeLibrary

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chap01_NativeLibrary
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_chap01_NativeLibrary_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
